-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiAutomations/db/wiki_automations_cron.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wiki_automations_cron (
  wac_automation_page INT UNSIGNED NOT NULL,
  wac_cron_expression VARBINARY(255) NOT NULL
) /*$wgDBTableOptions*/;
