-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiAutomations/db/wiki_automations_cron.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wiki_automations_cron (
  wac_automation_page INT NOT NULL, wac_cron_expression TEXT NOT NULL
);
